### ISSUE TITLE
command for a random crom emoji

### ISSUE THREAD

**Issue by ammongit** [crombird/issues#1]
There are lots of nice crom emojis, since the bot has "nitro" it would be cool if we could get a random one on command

![image](https://user-images.githubusercontent.com/8848022/81771924-605cb780-94b2-11ea-9239-aaa728d08d02.png)

**Comment by smlt** [comment]
closed: need more crom emojis  
please donate your spare crom emojis to p sherman, 42 wallaby way, sydney
